#!/bin/bash
git config --global user.email jxwazxzhp@126.com
git config --global user.name 'kabir'
git config --global core.editor vim
git config --system alias.st status
git config --system alias.ci commit
git config --system alias.co checkout
git config --system alias.br  branch
git config --global color.ui true


